# Generated by Django 3.1.3 on 2020-12-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccounthistory',
            name='courier_id',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='customeraccounthistory',
            name='description',
            field=models.FloatField(default='00', max_length=255),
        ),
        migrations.AddField(
            model_name='customeraccounthistory',
            name='staff_id',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='customerexpenseshistory',
            name='description',
            field=models.FloatField(default='00', max_length=255),
        ),
        migrations.AddField(
            model_name='customerexpenseshistory',
            name='staff_id',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='customerloanhistory',
            name='description',
            field=models.FloatField(default='00', max_length=255),
        ),
        migrations.AddField(
            model_name='customerloanhistory',
            name='staff_id',
            field=models.CharField(default='00', max_length=50),
        ),
    ]
