# Generated by Django 3.1.3 on 2020-12-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20201210_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='rub',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='uzs',
        ),
        migrations.RemoveField(
            model_name='customeraccounthistory',
            name='currency_type',
        ),
        migrations.RemoveField(
            model_name='customeraccounthistory',
            name='rub',
        ),
        migrations.RemoveField(
            model_name='customeraccounthistory',
            name='uzs',
        ),
        migrations.RemoveField(
            model_name='customerexpenses',
            name='rub',
        ),
        migrations.RemoveField(
            model_name='customerexpenses',
            name='uzs',
        ),
        migrations.RemoveField(
            model_name='customerexpenseshistory',
            name='currency_type',
        ),
        migrations.RemoveField(
            model_name='customerexpenseshistory',
            name='rub',
        ),
        migrations.RemoveField(
            model_name='customerexpenseshistory',
            name='uzs',
        ),
        migrations.RemoveField(
            model_name='customerloan',
            name='rub',
        ),
        migrations.RemoveField(
            model_name='customerloan',
            name='uzs',
        ),
        migrations.RemoveField(
            model_name='customerloanhistory',
            name='currency_type',
        ),
        migrations.RemoveField(
            model_name='customerloanhistory',
            name='rub',
        ),
        migrations.RemoveField(
            model_name='customerloanhistory',
            name='uzs',
        ),
    ]
