# Generated by Django 3.1.3 on 2020-12-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201210_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccounthistory',
            name='description',
            field=models.CharField(default='00', max_length=255),
        ),
    ]
