# Generated by Django 3.1.3 on 2020-12-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201210_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloanhistory',
            name='description',
            field=models.CharField(default='00', max_length=255),
        ),
    ]
