# Generated by Django 3.1.3 on 2020-12-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20201211_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerexpenseshistory',
            name='description',
            field=models.CharField(default='00', max_length=255),
        ),
    ]
