# Generated by Django 3.1.3 on 2020-12-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyhistory',
            old_name='rub',
            new_name='usd_rub',
        ),
        migrations.RenameField(
            model_name='currencyhistory',
            old_name='usd',
            new_name='usd_uzs',
        ),
        migrations.RemoveField(
            model_name='currencyhistory',
            name='uzs',
        ),
    ]
