# Generated by Django 3.1.3 on 2021-01-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_id', models.CharField(default='00', max_length=50)),
                ('sender_fio', models.CharField(default='00', max_length=255)),
                ('sender_phone', models.CharField(default='00', max_length=255)),
                ('sender_passport_number', models.CharField(default='00', max_length=255)),
                ('sender_passport_date_first', models.CharField(default='00', max_length=255)),
                ('sender_passport_date_second', models.CharField(default='00', max_length=255)),
                ('sender_passport_organization', models.CharField(default='00', max_length=255)),
                ('sender_organization', models.CharField(default='00', max_length=255)),
                ('sender_passport1', models.CharField(default='00', max_length=255)),
                ('sender_passport2', models.CharField(default='00', max_length=255)),
                ('sender_address', models.CharField(default='00', max_length=255)),
                ('recipient_phone', models.CharField(default='00', max_length=255)),
                ('recipient_passport_number', models.CharField(default='00', max_length=255)),
                ('recipient_passport_date_first', models.CharField(default='00', max_length=255)),
                ('recipient_passport_date_second', models.CharField(default='00', max_length=255)),
                ('recipient_passport_organization', models.CharField(default='00', max_length=255)),
                ('recipient_organization', models.CharField(default='00', max_length=255)),
                ('recipient_passport1', models.CharField(default='00', max_length=255)),
                ('recipient_passport2', models.CharField(default='00', max_length=255)),
                ('recipient_address', models.CharField(default='00', max_length=255)),
                ('parcel_plan', models.CharField(default='00', max_length=255)),
                ('parcel_cost', models.CharField(default='00', max_length=255)),
                ('parcel_from', models.CharField(default='00', max_length=255)),
                ('parcel_status', models.CharField(default='00', max_length=255)),
                ('parcel_length', models.FloatField(default='00', max_length=50)),
                ('parcel_height', models.FloatField(default='00', max_length=50)),
                ('parcel_weight', models.FloatField(default='00', max_length=50)),
                ('parcel_demension', models.FloatField(default='00', max_length=50)),
                ('description', models.CharField(default='00', max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_status', models.CharField(default='00', max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('parcelmain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.parcelmain')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_url', models.CharField(default='00', max_length=255)),
                ('prod_name', models.CharField(default='00', max_length=255)),
                ('prod_cnt', models.FloatField(default='00', max_length=50)),
                ('prod_cost', models.FloatField(default='00', max_length=50)),
                ('prod_tnved', models.CharField(default='00', max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('parcelmain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.parcelmain')),
            ],
        ),
    ]
