# Generated by Django 3.1.3 on 2021-01-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0003_parcelmain_parcel_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelmain',
            old_name='description',
            new_name='parcel_description',
        ),
        migrations.RenameField(
            model_name='parcelmain',
            old_name='parcel_demension',
            new_name='parcel_dimension',
        ),
        migrations.AlterField(
            model_name='parcelmain',
            name='parcel_cost',
            field=models.FloatField(default='00', max_length=255),
        ),
    ]
