# Generated by Django 3.1.3 on 2021-01-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0004_auto_20210113_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelmain',
            old_name='sender_fio',
            new_name='parcel_dostavka',
        ),
        migrations.AddField(
            model_name='parcelmain',
            name='parcel_zabor',
            field=models.CharField(default='00', max_length=255),
        ),
        migrations.AddField(
            model_name='parcelmain',
            name='recipient_id',
            field=models.CharField(default='00', max_length=255),
        ),
        migrations.AddField(
            model_name='parcelmain',
            name='sender_id',
            field=models.CharField(default='00', max_length=255),
        ),
    ]
