# Generated by Django 3.1.3 on 2021-01-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0005_auto_20210113_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelmain',
            name='recipient_address',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='recipient_organization',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='recipient_passport1',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='recipient_passport2',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='recipient_passport_date_first',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='recipient_passport_date_second',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='recipient_passport_number',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='recipient_passport_organization',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='recipient_phone',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='sender_address',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='sender_organization',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='sender_passport1',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='sender_passport2',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='sender_passport_date_first',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='sender_passport_date_second',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='sender_passport_number',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='sender_passport_organization',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='sender_phone',
        ),
    ]
