# Generated by Django 3.1.3 on 2021-01-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0006_auto_20210115_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelitems',
            name='prod_weight',
            field=models.FloatField(default='00', max_length=50),
        ),
    ]
