# Generated by Django 3.1.3 on 2021-01-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0008_auto_20210115_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelstatushistory',
            old_name='parcelmain_id',
            new_name='parcelmain',
        ),
    ]
