# Generated by Django 3.1.3 on 2021-01-15 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcel', '0009_auto_20210115_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelmain',
            name='recipient_id',
        ),
        migrations.RemoveField(
            model_name='parcelmain',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='parcelmain',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcelmain',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
