# Generated by Django 3.1.3 on 2021-01-16 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcel', '0010_auto_20210115_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelStatusName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_status', models.CharField(default='00', max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='parcelmain',
            name='courier_dostavka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_dostavka', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcelmain',
            name='courier_zabor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_zabor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcelmain',
            name='staff_recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcelmain',
            name='staff_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
