# Generated by Django 3.1.3 on 2021-01-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0011_auto_20210116_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelmain',
            name='parcel_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcel_status_current', to='parcel.parcelstatusname'),
        ),
        migrations.AlterField(
            model_name='parcelstatushistory',
            name='parcel_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcel_status_history', to='parcel.parcelstatusname'),
        ),
    ]
