# Generated by Django 3.1.3 on 2021-01-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0012_auto_20210116_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelitems',
            name='prod_image',
            field=models.ImageField(blank=True, default='passport_image.png', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='ParcelImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_image', models.ImageField(blank=True, default='passport_image.png', null=True, upload_to='photos/%Y/%m/%d/')),
                ('parcelmain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.parcelmain')),
            ],
        ),
    ]
