# Generated by Django 3.1.3 on 2021-01-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0013_auto_20210117_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelmain',
            name='parcel_image',
            field=models.ImageField(blank=True, default='passport_image.png', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='parcelmain',
            name='parcel_report_image',
            field=models.ImageField(blank=True, default='passport_image.png', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
