# Generated by Django 3.1.3 on 2021-01-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0017_auto_20210121_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelmain',
            name='parcel_dostavka',
            field=models.CharField(default='00', max_length=255),
        ),
        migrations.AddField(
            model_name='parcelmain',
            name='parcel_zabor',
            field=models.CharField(default='00', max_length=255),
        ),
    ]
