# Generated by Django 3.1.3 on 2021-01-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0018_auto_20210121_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelmain',
            name='parcel_getmoney_foritem',
            field=models.CharField(default='00', max_length=255),
        ),
    ]
