# Generated by Django 3.1.3 on 2021-01-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0019_parcelmain_parcel_getmoney_foritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelmain',
            name='parcel_item_total_cost',
            field=models.FloatField(default='00', max_length=255),
        ),
    ]
