# Generated by Django 3.1.3 on 2021-01-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0020_parcelmain_parcel_item_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelitems',
            name='prod_total_cost',
            field=models.FloatField(default='00', max_length=50),
        ),
    ]
