# Generated by Django 3.1.3 on 2021-01-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0021_parcelitems_prod_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelmain',
            name='parcel_dostavka_cost',
            field=models.FloatField(default='00', max_length=255),
        ),
        migrations.AddField(
            model_name='parcelmain',
            name='parcel_procent_prod_cost',
            field=models.FloatField(default='00', max_length=255),
        ),
        migrations.AddField(
            model_name='parcelmain',
            name='parcel_zabor_cost',
            field=models.FloatField(default='00', max_length=255),
        ),
        migrations.AlterField(
            model_name='parcelmain',
            name='parcel_getmoney_foritem',
            field=models.FloatField(default='00', max_length=255),
        ),
    ]
