# Generated by Django 3.1.3 on 2021-01-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0023_auto_20210123_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelmain',
            name='parcel_dostavka',
            field=models.CharField(default='off', max_length=255),
        ),
        migrations.AlterField(
            model_name='parcelmain',
            name='parcel_getmoney_foritem',
            field=models.CharField(default='off', max_length=255),
        ),
        migrations.AlterField(
            model_name='parcelmain',
            name='parcel_zabor',
            field=models.CharField(default='off', max_length=255),
        ),
    ]
