# Generated by Django 3.1.3 on 2021-01-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0025_parcelservicecost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParcelServiceCost',
        ),
    ]
