# Generated by Django 3.1.3 on 2020-12-05 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.FloatField(default='00', max_length=255)),
                ('rub', models.FloatField(default='00', max_length=255)),
                ('uzs', models.FloatField(default='00', max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.FloatField(default='00', max_length=255)),
                ('rub', models.FloatField(default='00', max_length=255)),
                ('uzs', models.FloatField(default='00', max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyExpensesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_id', models.CharField(default='00', max_length=50)),
                ('usd', models.FloatField(default='00', max_length=255)),
                ('rub', models.FloatField(default='00', max_length=255)),
                ('uzs', models.FloatField(default='00', max_length=255)),
                ('currency_type', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('UZS', 'UZS')], default=True, max_length=50)),
                ('company_expenses_type', models.CharField(choices=[('Мелкие расходы', 'Мелкие расходы'), ('Зарплата', 'Зарплата'), ('Обед', 'Обед'), ('Бензин', 'Бензин'), ('Еб куйдик', 'Еб куйдик'), ('Прочие', 'Прочие'), ('За долг', 'За долг')], default='00', max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('customer_loan_history', models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, to='customer.customerloanhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAccountHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_id', models.CharField(default='00', max_length=50)),
                ('usd', models.FloatField(default='00', max_length=255)),
                ('rub', models.FloatField(default='00', max_length=255)),
                ('uzs', models.FloatField(default='00', max_length=255)),
                ('currency_type', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('UZS', 'UZS')], default=True, max_length=50)),
                ('service_type', models.CharField(choices=[('За Товар', 'За Товар'), ('За перевозку Москва-Ташкент', 'За перевозку Москва-Ташкент'), ('За перевозку Ташкент-Москва', 'За перевозку Ташкент-Москва')], default='00', max_length=50)),
                ('plan_type', models.CharField(choices=[('Эконом Москва-Ташкент', 'Эконом Москва-Ташкент'), ('Эконом Ташкент-Москва', 'Эконом Ташкент-Москва'), ('Стандарт Москва-Ташкент', 'Стандарт Москва-Ташкент'), ('Стандарт Ташкент-Москва', 'Стандарт Ташкент-Москва'), ('Ултрасрочный Москва-Ташкент', 'Ултрасрочный Москва-Ташкент'), ('Ултрасрочный Ташкент-Москва', 'Ултрасрочный Ташкент-Москва'), ('Духи Москва-Ташкент', 'Духи Москва-Ташкент'), ('Лекарство Москва-Ташкент', 'Лекарство Москва-Ташкент')], default='00', max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
