# Generated by Django 3.1.3 on 2020-12-08 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOwnExpensesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_id', models.CharField(default='00', max_length=50)),
                ('usd', models.FloatField(default='00', max_length=255)),
                ('rub', models.FloatField(default='00', max_length=255)),
                ('uzs', models.FloatField(default='00', max_length=255)),
                ('currency_type', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('UZS', 'UZS')], default=True, max_length=50)),
                ('company_expenses_type', models.CharField(choices=[('Мелкие расходы', 'Мелкие расходы'), ('Зарплата', 'Зарплата'), ('Обед', 'Обед'), ('Бензин', 'Бензин'), ('Еб куйдик', 'Еб куйдик'), ('Прочие', 'Прочие'), ('За долг', 'За долг')], default='00', max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
