# Generated by Django 3.1.3 on 2020-12-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyownexpenseshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaccount',
            name='rub',
        ),
        migrations.RemoveField(
            model_name='companyaccount',
            name='uzs',
        ),
        migrations.RemoveField(
            model_name='companyaccounthistory',
            name='currency_type',
        ),
        migrations.RemoveField(
            model_name='companyaccounthistory',
            name='rub',
        ),
        migrations.RemoveField(
            model_name='companyaccounthistory',
            name='uzs',
        ),
        migrations.RemoveField(
            model_name='companyexpenses',
            name='rub',
        ),
        migrations.RemoveField(
            model_name='companyexpenses',
            name='uzs',
        ),
        migrations.RemoveField(
            model_name='companyexpenseshistory',
            name='currency_type',
        ),
        migrations.RemoveField(
            model_name='companyexpenseshistory',
            name='rub',
        ),
        migrations.RemoveField(
            model_name='companyexpenseshistory',
            name='uzs',
        ),
        migrations.RemoveField(
            model_name='companyownexpenseshistory',
            name='rub',
        ),
        migrations.RemoveField(
            model_name='companyownexpenseshistory',
            name='uzs',
        ),
    ]
