# Generated by Django 3.1.3 on 2020-12-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201211_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccounthistory',
            name='staff_id',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='companyexpenseshistory',
            name='staff_id',
            field=models.CharField(default='00', max_length=50),
        ),
        migrations.AddField(
            model_name='companyownexpenseshistory',
            name='staff_id',
            field=models.CharField(default='00', max_length=50),
        ),
    ]
