# Generated by Django 3.1.3 on 2021-01-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_companyownexpenseshistory_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccounthistory',
            name='service_type',
            field=models.CharField(choices=[('За Товар', 'За Товар'), ('За перевозку Москва-Ташкент', 'За перевозку Москва-Ташкент'), ('За перевозку Ташкент-Москва', 'За перевозку Ташкент-Москва'), ('Вернуть клиенту', 'Вернуть клиенту')], default='00', max_length=50),
        ),
    ]
